### ISSUE TITLE
Feature: Ideal weight by height

### ISSUE THREAD

**Issue by sergiodxa** [codeableorg/weight-tracker-app#7]
**Describe the solution you'd like**
As a user, I want to know my ideal weight based on my height and gender.

- [x] The application should ask my gender.
- [x] Based on my gender and height it should calculate my ideal weight.
- [x] It should show my ideal weight as a fixed milestone (#3) after defined the gender.

**Comment by luciagirasoles** [comment]
Features were verified in the project.
